# Generated by Django 6.0.6 on 2026-06-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('is_critical', models.BooleanField(default=False)),
            ],
        ),
    ]
