# Generated by Django 6.0.6 on 2026-06-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Tienda / Comercio')),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Encargado')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('address', models.TextField(verbose_name='Dirección Completa / Ruta de Entrega')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Límite de Crédito')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Pendiente')),
                ('status', models.CharField(choices=[('EXCELLENT', 'Excelente (Al día)'), ('ALERT', 'Alerta de Stock (Próximo a agotarse)'), ('LATE', 'Moroso (Bloqueado)')], default='EXCELLENT', max_length=15, verbose_name='Estado de Cobranza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-id'],
            },
        ),
    ]
