# Generated by Django 6.0.6 on 2026-07-08 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sale_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='client',
            name='current_balance',
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(verbose_name='Dirección Exacta'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RouteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('VISITED', 'VISITED'), ('NO_SALE', 'NO_SALE')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('planned_date', models.DateField(auto_now_add=True)),
                ('sequence_order', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_visits', to='inventory.client')),
            ],
            options={
                'verbose_name': 'Visita de Ruta',
                'verbose_name_plural': 'Visitas de Ruta',
                'ordering': ['sequence_order'],
            },
        ),
    ]
